FROM alpine:3.19
ARG GOBGP_VERSION=3.30.0
RUN apk add --no-cache gettext ca-certificates \
    && wget -qO- \
       "https://github.com/osrg/gobgp/releases/download/v${GOBGP_VERSION}/gobgp_${GOBGP_VERSION}_linux_amd64.tar.gz" \
       | tar xz -C /usr/local/bin gobgpd gobgp
COPY docker/gobgp/gobgp.conf.tmpl /etc/gobgp/gobgp.conf.tmpl
COPY docker/gobgp/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
